version: '3.1'

services:
  db:
    container_name: postgres
    image: 'postgis/postgis:14-3.2-alpine'
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
